### ISSUE TITLE
wrong-number-of-arguments (3 . 3), 2

### ISSUE THREAD

**Issue by Vonfry** [haskell/haskell-mode#1691]
It starts from commits 4d77a88a2cb14ff6b9672c1503c46086300f94e7.

Some details: [travis-ci](https://travis-ci.org/haskell/haskell-mode/jobs/626987871#L375-L376)

cc: @purcell

**Comment by guygastineau** [comment]
I am experiencing this tonight as well.

**Comment by guygastineau** [comment]
This is line 139 of `haskell-interactive-mode.el`:
``` elisp
(define-obsolete-face-alias 'haskell-interactive-face-prompt2 'haskell-interactive-face-prompt-cont)
```
Unfortunately, the macro `define-obsolete-face-alias` requires 3 arguments.
``` elisp
(defmacro define-obsolete-face-alias (obsolete-face current-face when)
  "Make OBSOLETE-FACE a face alias for CURRENT-FACE and mark it obsolete.                                             
If provided, WHEN should be a string indicating when the face                                                         
was first made obsolete, for example a date or a release number."
  `(progn
     (put ,obsolete-face 'face-alias ,current-face)
     ;; Used by M-x describe-face.                                                                                    
     (put ,obsolete-face 'obsolete-face (or (purecopy ,when) t))))
```

**Comment by qcfu-bu** [comment]
I am having the same issue. From the way the comment in the macro is worded, it should be able to take either 2 or 3 arguments?

**Comment by guygastineau** [comment]
@qcfu-bu thank you for that clarification.

I think I didn't really read the docstrings, because I was already thinking about what the debug messages told me.

I wonder why this is happening then. I am not used to elisp macros (I'm used to scheme macros). Do elisp macros need to state optional args as optional?

**Comment by qcfu-bu** [comment]
I believe there should be an optional argument, though I may be wrong.

[https://www.gnu.org/software/emacs/manual/html_node/eintr/Optional-Arguments.html](url)

**Comment by guygastineau** [comment]
Yeah, reading some documentation it seems like `&optional` can be used with `defmacro`, so perhaps that is the problem here.

I can't actually tell where `define-obsolete-face-alias` is defined (I got the source from the debugger, but it came from a byte code run and it didn't give me the source location).  If it is from another package, then maybe it needs to be fixed there.

I excluded the comment that preceded it in the source. That comment basically said, "the following macro doesn't do anything, and don't use it."

So I don't really know where this leads us, but maybe that information is helpful to someone.

**Comment by jfb-ampli** [comment]
It seems to be defined in `lisp/emacs-lisp/byte-run.el` in the Emacs source. Seems like adding a `&optional` there would do the trick? I'll build and check.

**Comment by guygastineau** [comment]
@jfb-ampli thank you. Hmm, I guess I saw `byte-run`, and I assumed it was a compiler pass. I didn't realize that was actually a src file.

Do you know where to make a PR to patch `byte-run.el` if you patch works?

**Comment by gbrls** [comment]
@guygastineau Can you explain a little further your workaround?

**Comment by jfb-ampli** [comment]
It did work. I'll check out how to push a patch upstream. Off to `emacs-devel`, I guess.

**Comment by guygastineau** [comment]
@jfb-ampli you are my hero :heart_eyes: 

@gbrls 
It seems like @jfb-ampli is going to submit a patch to main emacs which should fix this.

In the mean time (I haven't tried this, but it should work) you can change line 139 of `haskell-interactive-mode.el` in this package from:
``` elisp
(define-obsolete-face-alias 'haskell-interactive-face-prompt2 'haskell-interactive-face-prompt-cont)
```
to
``` elisp
(define-obsolete-face-alias 'haskell-interactive-face-prompt2 'haskell-interactive-face-prompt-cont t)
```
-----
Made a bit clearer that would be:
``` elisp
(define-obsolete-face-alias
 'haskell-interactive-face-prompt2
 'haskell-interactive-face-prompt-cont
 t)
```

We are just adding the default arg for the macro explicitly, because the macro failed to make the third argument optional.  This has probably gone unnoticed, because the documentation for it says not to use the macro anyway.

**Comment by gbrls** [comment]
Just made a fork with this modification https://github.com/gbrls/haskell-mode/commit/97a33fc63547ccc1e58a9a61953bcacee3a41b0f
Updated my `package.el` to use it and it still throws the same error:
```Error with packages (doom-package-error)
  (wrong-number-of-arguments (3 . 3) 2)
```

**Comment by qcfu-bu** [comment]
@guygastineau Your solution worked for me. From looking at the commit that broke this, it puzzles me as to what purpose `define-obsolete-face-alias` served.

**Comment by guygastineau** [comment]
@qcfu-bu exactly what I was thinking.

@gbrls I am not sure what to say.  I am not really any sort of expert at emacs (in fact I just switched from doom and spacemacs to my own config).  I am a Scheme/Lisp nerd, so most of the time I try to transfer those skills to elisp.

**Comment by jfb-ampli** [comment]
I have submitted a bug-report and patch to the emacs bug list. I'll link whatever information I get here.

**Comment by jfb-ampli** [comment]
Here's the bug report, fyi:

`define-obsolete-face-alias` claims not to require the third argument,
`when`. However, `when` is not defined `&optional`. This patch addresses
this.
---
 lisp/emacs-lisp/byte-run.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lisp/emacs-lisp/byte-run.el b/lisp/emacs-lisp/byte-run.el
index 1115c09667..27aee3ed4e 100644
--- a/lisp/emacs-lisp/byte-run.el
+++ b/lisp/emacs-lisp/byte-run.el
@@ -448,7 +448,7 @@ CURRENT-NAME, if it does not already have them:
 ;; by the byte-compiler (would be nice if it could warn about obsolete
 ;; faces, but it doesn't really do anything special with faces).
 ;; It only really affects M-x describe-face output.
-(defmacro define-obsolete-face-alias (obsolete-face current-face when)
+(defmacro define-obsolete-face-alias (obsolete-face current-face &optional when)
   "Make OBSOLETE-FACE a face alias for CURRENT-FACE and mark it obsolete.
 If provided, WHEN should be a string indicating when the face
 was first made obsolete, for example a date or a release number."
--
2.21.0 (Apple Git-122.2)

**Comment by guygastineau** [comment]
I wonder if we should still try changing the code from this end too, since a lot of users will likely have to wait a long time to get this patch if they are using emacs from their distro's package manager... ?

**Comment by jfb-ampli** [comment]
Yeah, I think it makes sense to patch locally, because it's going to move a lot faster here than upstream.

**Comment by jfb-ampli** [comment]
https://github.com/haskell/haskell-mode/pull/1692

**Comment by purcell** [comment]
Fixed now, sorry, my bad: I missed that this had broken CI. I was trying to catch up a little on PRs and issues, and broke this along the way. The commit had added both a `define-obsolete-variable-alias` and `define-obsolete-face-alias`, and I knew that the "when" arg was optional for the former, and didn't check the latter. Sorry for the inconvenience.

**Comment by purcell** [comment]
I've also forced a build of the MELPA package, so the fixed version is immediately installable.

**Comment by guygastineau** [comment]
@purcell your work is very appreciated!

**Comment by jfb-ampli** [comment]
Thanks, @purcell !
